### ISSUE TITLE
Integrating with @middy/secrets-manager using internalData

### ISSUE THREAD

**Issue by ruxta** [willfarrell/middy-rds#10]
I'm trying to integrate this with @middy/secrets-manager, but setting internalData isn't working.

My DB conn is stored in secrets manager like:
```JSON
{
	"host": "***.rds.amazonaws.com",
	"port": 3306,
	"user": "***",
	"password": "***",
	"database": "***"
}
```

Handler is:
```JS
const handler = middy()
	.use(
		secretsManager({
			fetchData: {
				dbConn: 'SECRET_NAME',
			},
		}),
	)
	.use(
		rdsMiddleware({
			client: knex,
			config: {
				client: 'mysql2',
			},
			internalData: 'dbConn',
		}),
	)
	.handler(async (event, context) => {
		const { sql } = context;

		// ...
	});
```

Issue is options.config.connection ends up being:
```JSON
{
	"dbConn": {
		"host": "***.rds.amazonaws.com",
		"port": 3306,
		"user": "***",
		"password": "***",
		"database": "***"
	},
	"ssl": { ... }
}
```

Expected:
```JSON
{
	"host": "***.rds.amazonaws.com",
	"port": 3306,
	"user": "***",
	"password": "***",
	"database": "***",
	"ssl": { ... }
}
```

https://github.com/willfarrell/middy-rds/blob/2e5834996ec68b8d69221ca45d9eaa0494aee162/clients/knex.js#L24-L29

If I change line 28 to this it works:
```JS
      ...values[options.internalData]
```

**Comment by willfarrell** [comment]
There was `@middy/db-manager` that did this (from what I recall) but it was deprecated due to low usage and being time consuming to maintain well. RDS Signer, what this packages uses, is free, faster, and more secure compared to Secrets Manager. Adding Secrets Manager support adds additional complexity that I'm not looking to support at this time.
